AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "app.rb"
    - "bench/**/*"
    - "lib/saratoga/schema.rb"
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "lib/gen_ql/executor.rb"

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "lib/gen_ql/executor.rb"

Metrics/CyclomaticComplexity:
  Max: 15

Layout/LineLength:
  Max: 120

Naming/MethodParameterName:
  AllowedNames:
    - db
    - e
    - k
    - v
    - f

Metrics/ModuleLength:
  Exclude:
    - "lib/saratoga/database.rb"
    - "lib/saratoga/schema.rb"

Metrics/ClassLength:
  Exclude:
    - "app.rb"
    - "lib/saratoga/database.rb"
    - "lib/gen_ql/executor.rb"
