AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 15

Layout/LineLength:
  Max: 120

Naming/MethodParameterName:
  AllowedNames:
    - db
    - e
    - k
    - v
    - f

Metrics/ModuleLength:
  Exclude:
    - "lib/saratoga/database.rb"

Metrics/ClassLength:
  Exclude:
    - "lib/saratoga/database.rb"
